
name: CI

permissions:
  id-token: write # required to use OIDC authentication
  contents: read # required to checkout the code from the repo

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  S3_BUCKET: "s3://wordle-archive20220621134744327500000005/"
  AWS_ROLE: "arn:aws:iam::846359942316:role/github-oidc-wordle-archive"

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{env.AWS_ROLE}}
          role-duration-seconds: 3600
          aws-region: us-east-1

      - name: Docker build
        run: docker build -t wordle_archive . 

      - name: Docker create
        run: docker create --name wordle_archive wordle_archive

      - name: Docker cp
        run: docker cp wordle_archive:/usr/share/nginx/html/wordle_archive ./wordle_archive

      - name: S3 sync
        run: aws s3 sync ./wordle_archive $S3_BUCKET
